#!/usr/bin/env python3
"""
OpenWeather API Client for weather_broadcaster role

This tool was automatically generated by tool_generator.py
Description: Get weather information and forecasts from OpenWeather API
Authentication: api_key
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import sys
from typing import Dict, Optional, Any, List
import requests

CONFIG_DIR = Path.home() / ".config" / "roles-skill" / "weather_broadcaster"
CONFIG_FILE = CONFIG_DIR / "openweather.json"


class OpenWeatherClient:
    """OpenWeather API Client"""

    def __init__(self):
        self.config = self.load_config()
        self.api_key = self.config.get("api_key")
        self.api_base = "https://api.openweathermap.org/data/2.5"

    def load_config(self) -> Dict[str, Any]:
        """Load configuration from file"""
        if not CONFIG_DIR.exists():
            CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        if not CONFIG_FILE.exists():
            return {}
        with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
            return json.load(f)

    def save_config(self, config: Dict[str, Any]) -> None:
        """Save configuration to file"""
        if not CONFIG_DIR.exists():
            CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        with open(CONFIG_FILE, 'w', encoding='utf-8') as f:
            json.dump(config, f, indent=2)

    def setup(self, api_key: str) -> None:
        """Interactive setup for API credentials"""
        self.config["api_key"] = api_key
        self.save_config(self.config)
        self.api_key = api_key
        print("✓ OpenWeather configuration saved")

    def is_configured(self) -> bool:
        """Check if API key is configured"""
        return self.api_key is not None and self.api_key != ""

    def api_get(self, endpoint: str, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Make GET request to OpenWeather API"""
        if not self.is_configured():
            raise ValueError("API key not configured. Run setup first.")

        url = f"{self.api_base}/{endpoint}"
        if params is None:
            params = {}
        params["appid"] = self.api_key

        response = requests.get(url, params=params)
        response.raise_for_status()
        return response.json()

    def get_current_weather(self, city: str, country_code: Optional[str] = None, units: str = "metric") -> Dict[str, Any]:
        """Get current weather for a city"""
        q = city
        if country_code:
            q = f"{city},{country_code}"

        return self.api_get("weather", {
            "q": q,
            "units": units
        })

    def get_forecast(self, city: str, country_code: Optional[str] = None, days: int = 5, units: str = "metric") -> Dict[str, Any]:
        """Get 5-day forecast for a city"""
        q = city
        if country_code:
            q = f"{city},{country_code}"

        return self.api_get("forecast", {
            "q": q,
            "cnt": days * 8,  # 3-hour intervals
            "units": units
        })


def main():
    """CLI interface for testing"""
    import argparse
    parser = argparse.ArgumentParser(description="OpenWeather API Client")
    parser.add_argument("--setup", action="store_true", help="Setup API credentials")
    parser.add_argument("--api-key", type=str, help="API key for setup")
    parser.add_argument("--current", type=str, help="Get current weather for city")
    parser.add_argument("--country", type=str, help="Country code for city")
    parser.add_argument("--forecast", type=str, help="Get forecast for city")

    args = parser.parse_args()

    client = OpenWeatherClient()

    if args.setup:
        if not args.api_key:
            print("Error: --api-key is required for setup")
            sys.exit(1)
        client.setup(args.api_key)
        return

    if args.current:
        if not client.is_configured():
            print("Error: Not configured. Run --setup first")
            sys.exit(1)
        result = client.get_current_weather(args.current, args.country)
        print(json.dumps(result, indent=2, ensure_ascii=False))
        return

    if args.forecast:
        if not client.is_configured():
            print("Error: Not configured. Run --setup first")
            sys.exit(1)
        result = client.get_forecast(args.forecast, args.country)
        print(json.dumps(result, indent=2, ensure_ascii=False))
        return


if __name__ == "__main__":
    main()
